/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package praktikum.pkg11.pkg12;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
/**
 *
 * @author CHAIRULAW
 */
public class formkrs extends javax.swing.JFrame {
public Connection conn;
public Statement cn;
    /**
     * Creates new form formkrs
     */
    public formkrs() {
        initComponents();
        bersih();
        tabelformkrs.setModel(tblmodel);
    }
    
    String data[] = new String[3];
    private javax.swing.table.DefaultTableModel tblmodel=getDefaultTableModel();
    int row =0;
    
    private javax.swing.table.DefaultTableModel getDefaultTableModel(){
        return new javax.swing.table.DefaultTableModel( 
                new Object[][]{},new String[]{"Kode","Matakuliah" ,"SKS"}
        );       
    }
    
     public void koneksi(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection
        ("jdbc:mysql://localhost:3306/dbakademik","root","");
            cn= conn.createStatement();
        }catch (Exception e){JOptionPane.showMessageDialog(null,"koneksi gagal..");
        System.out.println(e.getMessage());
        }
    }
        
            void cekkrs(){
            DefaultTableModel tabelnyo=new DefaultTableModel();
            tabelnyo.addColumn("Kode");
            tabelnyo.addColumn("Nama Matakuliah");
            tabelnyo.addColumn("SKS");

            try{
                koneksi();
                String sql = "SELECT NO_KRS,KRS_SEMESTER,KRS_KDMTK,"
                        + "KRS_NIM,Namamhs,NILAI,NILAI,NILAI "
                        + "FROM krs join mahasiswa on KRS_NIM=NIMmhs "
                        + "join matakuliah on KRS_KDMTK=KODE_MTK"
                        +  "  WHERE  KRS_SEMESTER='"+  txtsem.getText()  +"'  AND  KRS_SEMESTER='"
                        + txtnim.getText() +"'";
                ResultSet rs = cn.executeQuery(sql);
                while (rs.next()) {
                    tabelnyo.addRow(new Object[]{
                        rs.getString(3),
                        rs.getString(7),
                        rs.getString(8)
                    });
                }
                jTable2.setModel(tabelnyo);
            }catch (Exception e){
                JOptionPane.showMessageDialog(null,"Kesalahan Menampilkan Data"+ e);
            }
        }
            
            void bersih(){
                txtsem.setText("");
                txtnim.setText("");
                txtnama.setText("");
                txtkodemtk.setText("");
                txtnamamtk.setText("");
                txtsks.setText("");
            }      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtsem = new javax.swing.JTextField();
        txtnim = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtkodemtk = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtnamamtk = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtsks = new javax.swing.JTextField();
        BTtambah = new javax.swing.JButton();
        BThapus = new javax.swing.JButton();
        BTcarikode = new javax.swing.JButton();
        BTcarinim = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelformkrs = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SEMESTER");

        jLabel2.setText("NIM MAHASISWA");

        jLabel3.setText("CONTOH: 21022");

        jLabel4.setText("NAMA");

        txtnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnimActionPerformed(evt);
            }
        });
        txtnim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnimKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        jLabel5.setText("KODE MTK");

        jLabel6.setText("MATAKULIAH");

        jLabel7.setText("SKS");

        BTtambah.setText("+");
        BTtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTtambahActionPerformed(evt);
            }
        });

        BThapus.setText("-");
        BThapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BThapusActionPerformed(evt);
            }
        });

        BTcarikode.setText("CARI");
        BTcarikode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTcarikodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtkodemtk, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtnamamtk, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtsks, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(BTtambah)
                        .addGap(72, 72, 72)
                        .addComponent(BThapus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BTcarikode)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkodemtk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnamamtk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTtambah)
                    .addComponent(BThapus))
                .addGap(26, 26, 26)
                .addComponent(BTcarikode)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        BTcarinim.setText("CARI");
        BTcarinim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTcarinimActionPerformed(evt);
            }
        });

        tabelformkrs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelformkrs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelformkrsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelformkrs);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton5.setText("SIMPAN");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("KELUAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtnim)
                                    .addComponent(txtsem, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                                .addGap(110, 110, 110)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(38, 38, 38)
                                        .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(BTcarinim)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(113, 113, 113)
                                .addComponent(jButton6)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtsem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addComponent(BTcarinim)
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnimActionPerformed
        // TODO add your handling code here:
        cekkrs();
    }//GEN-LAST:event_txtnimActionPerformed

    private void txtnimKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnimKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            try{
                koneksi();
                String sql = "Select * from mahasiswa_2221026 where NIMmhs='"+txtnim.getText()+"'";
                ResultSet rs = cn.executeQuery(sql);
                
                if (rs.next()){
                    txtnama.setText(rs.getString(2));
                    txtkodemtk.requestFocus();
                    
                }else{
                    JOptionPane.showMessageDialog(null,"Data Mahasiswa Tidak Ada");
                    txtnim.requestFocus();
                }
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, "Ada Kesalahan Menampilkan Data Mahasiswa" + e);
            }
        }     
    }//GEN-LAST:event_txtnimKeyPressed

    private void BTtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTtambahActionPerformed
        // TODO add your handling code here:
        String k = txtkodemtk.getText();
        if (k.equals("")){
            JOptionPane.showMessageDialog(null, "Kode Matakuliah Belum Diisi");
        }
        else{data[0]= txtkodemtk.getText();
        data[1]= txtnamamtk.getText();
        data[2]= txtsks.getText();
        tblmodel.insertRow(row, data);
        txtkodemtk.setText("");
        txtnamamtk.setText("");
        txtsks.setText("");}     
    }//GEN-LAST:event_BTtambahActionPerformed

    private void BThapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BThapusActionPerformed
        // TODO add your handling code here:
        tblmodel.removeRow(row);
        txtkodemtk.setText("");
        txtnamamtk.setText("");
        txtsks.setText("");
    }//GEN-LAST:event_BThapusActionPerformed

    private void tabelformkrsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelformkrsMouseClicked
        // TODO add your handling code here:
        row = tabelformkrs.getSelectedRow();
        txtkodemtk.setText(tblmodel.getValueAt(row, 0).toString());
        txtnamamtk.setText(tblmodel.getValueAt(row, 1).toString());
        txtsks.setText(tblmodel.getValueAt(row, 2).toString());
    }//GEN-LAST:event_tabelformkrsMouseClicked

    private void BTcarikodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTcarikodeActionPerformed
        // TODO add your handling code here:
        new formcarikodemtk().show();
    }//GEN-LAST:event_BTcarikodeActionPerformed

    private void BTcarinimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTcarinimActionPerformed
        // TODO add your handling code here:
        new formcarimhs().show();
    }//GEN-LAST:event_BTcarinimActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try{
        koneksi();
        String sql = "insert into mahasiswa_2221026 values('"+ txtsem.getText() +"','"+ txtnim.getText() +"','"+
                txtnama.getText() +"','"+ txtkodemtk.getText() +"','"+ txtnamamtk.getText() +"','"+ txtsks.getText() +"'";
        cn.executeUpdate(sql);
        conn.close();
        bersih();
        JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Proses Penyimpanan Data Gagal" + e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formkrs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formkrs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formkrs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formkrs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formkrs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTcarikode;
    private javax.swing.JButton BTcarinim;
    private javax.swing.JButton BThapus;
    private javax.swing.JButton BTtambah;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tabelformkrs;
    public static javax.swing.JTextField txtkodemtk;
    public static javax.swing.JTextField txtnama;
    public static javax.swing.JTextField txtnamamtk;
    public static javax.swing.JTextField txtnim;
    public static javax.swing.JTextField txtsem;
    public static javax.swing.JTextField txtsks;
    // End of variables declaration//GEN-END:variables
}
