/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package praktikum.pkg9;
import java.sql.ResultSet;
import java.sql.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.table.*;
import javax.swing.*;
/**
 *
 * @author CHAIRULAW
 */
public class inputmatkul extends javax.swing.JFrame {
public Connection conn;
public Statement cn;
    /**
     * Creates new form menu
     */
    public inputmatkul() {
        initComponents();
        tampildata();
        bersih();
    }

     public void koneksi(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection
        ("jdbc:mysql://localhost:3306/dbakademik","root","");
            cn= conn.createStatement();
        }catch (Exception e){JOptionPane.showMessageDialog(null,"koneksi gagal..");
        System.out.println(e.getMessage());
        }
    }
     
    public void tampildata(){
    DefaultTableModel tabelnyo = new DefaultTableModel();
    tabelnyo.addColumn("Kode Matakuliah");
    tabelnyo.addColumn("Nama Matakuliah");
    tabelnyo.addColumn("SKS");
    
    
    try{
        koneksi();
        String sql = "SELECT * FROM matakuliah_2221026";
        ResultSet rs = cn.executeQuery(sql);
        while (rs.next()) {
            tabelnyo.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3)
            });
        }
        
        tabelinput.setModel(tabelnyo);
    }catch (Exception e){
        JOptionPane.showMessageDialog(null, "Ada Kesalahan");
    }
}

     
     public void validasiMATKUL(){
         try {
            koneksi();
            String sql = "SELECT * FROM matakuliah WHERE KODE_MTK='" + JtxtKDmtk.getText() + "'";
            ResultSet rs = cn.executeQuery(sql);
            if (rs.next()) {
                JtxtKDmtk.setText(rs.getString("KODE_MTK"));
                JTxtNamaMtk.setText(rs.getString("NAMA_MTK"));
                JTxtJmlsks.setText(rs.getString(3));

                JBtnEdit.setEnabled(true);
                JBTnSave.setEnabled(false);

                try {
                    int kel = JOptionPane.showConfirmDialog(this, "Kode Matakuliah: " + JtxtKDmtk.getText() + " sudah ada. Apakah ingin diubah atau dihapus?",
                            "INFORMASI", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                    if (kel == JOptionPane.NO_OPTION) {
                        bersih();
                        JBtnEdit.setEnabled(true);
                        JBTnSave.setEnabled(true);
                        JtxtKDmtk.requestFocus();
                        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    }
                } catch (Exception e) {
                    // Penanganan Exception di sini
                }
            }
        } catch (Exception e) {
            // Penanganan Exception di sini
        }
    }


    public void Cari(){
    String a = txtcari.getText();
    if (a.equals("")) {
        JOptionPane.showMessageDialog(null, "Field Masih kosong..", "INFORMASI", JOptionPane.INFORMATION_MESSAGE);
        txtcari.requestFocus();
    } else {
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("KODE_MTK");
        tabel.addColumn("NAMA_MTK");
        tabel.addColumn("SKS");
        try {
            koneksi();
            String sql = "SELECT * FROM matakuliah_2221026 WHERE Kodemtk LIKE '%" + txtcari.getText() + "%' OR Namamtk LIKE '%" + txtcari.getText() + "%'";
            ResultSet rs = cn.executeQuery(sql);
            while (rs.next()) {
                tabel.addRow(new Object[]{
                        rs.getString(1),
                        rs.getString(2),
                        rs.getString(3)
                });
            }
            tabelinput.setModel(tabel);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan..", "INFORMASI", JOptionPane.INFORMATION_MESSAGE);
        }
    }
}


public void bersih(){
    
    txtcari.setText("");
    JtxtKDmtk.setText("");
    JTxtNamaMtk.setText("");
    JTxtJmlsks.setText("");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JBTnSave = new javax.swing.JButton();
        JtxtKDmtk = new javax.swing.JTextField();
        JTxtNamaMtk = new javax.swing.JTextField();
        JTxtJmlsks = new javax.swing.JTextField();
        JBtnEdit = new javax.swing.JButton();
        JBtnHapus = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelinput = new javax.swing.JTable();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel1.setText("INPUT DATA MATAKULIAH");

        jLabel2.setText("Cari berdasarkan nama matakuliah");

        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });

        jLabel3.setText("Kode Matakuliah");

        jLabel4.setText("Nama Matakuliah");

        jLabel5.setText("SKS");

        JBTnSave.setText("Simpan");
        JBTnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTnSaveActionPerformed(evt);
            }
        });

        JtxtKDmtk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtKDmtkActionPerformed(evt);
            }
        });

        JBtnEdit.setText("Edit");
        JBtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnEditActionPerformed(evt);
            }
        });

        JBtnHapus.setText("Hapus");
        JBtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnHapusActionPerformed(evt);
            }
        });

        jButton4.setText("Keluar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tabelinput.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelinput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelinputMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelinput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JtxtKDmtk)
                            .addComponent(JTxtNamaMtk)
                            .addComponent(JTxtJmlsks, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JBTnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBtnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBtnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(JBTnSave)
                            .addComponent(JtxtKDmtk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(JTxtNamaMtk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBtnEdit))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(JTxtJmlsks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBtnHapus))
                        .addGap(32, 32, 32)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtxtKDmtkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtKDmtkActionPerformed
        // TODO add your handling code here:
        validasiMATKUL();
    }//GEN-LAST:event_JtxtKDmtkActionPerformed

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
        Cari();
    }//GEN-LAST:event_txtcariActionPerformed

    private void JBTnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTnSaveActionPerformed
        // TODO add your handling code here:
        try{
            koneksi();
            String sql = "insert into matakuliah_2221026 values('"+ JtxtKDmtk.getText() +"','"+ JTxtNamaMtk.getText() +"','"+  
                    JTxtJmlsks.getText() +"')";
            cn.executeUpdate(sql);
            conn.close();
            tampildata();
            bersih();
            JOptionPane.showMessageDialog(null,"Data berhasil di simpan"); 
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Proses penyimpanan gagal" + e); 
        }
    }//GEN-LAST:event_JBTnSaveActionPerformed

    private void JBtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnEditActionPerformed
        // TODO add your handling code here:
        try {
            koneksi();
            String sql = "update matakuliah_2221026 set Namamtk='"+ JTxtNamaMtk.getText() +"'," +
                    "Sks='" + JTxtJmlsks.getText() + "'" +
                    "where Kodemtk='" + JtxtKDmtk.getText() + "'";
            cn.executeUpdate(sql);
            conn.close();
            tampildata();
            bersih();
            
            JtxtKDmtk.setEnabled(true);
            JBTnSave.setEnabled(true);
            JtxtKDmtk.requestFocus();
            JBtnEdit.setEnabled(false);
            JBtnHapus.setEnabled(false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_JBtnEditActionPerformed

    private void JBtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnHapusActionPerformed
        // TODO add your handling code here:
        try {
            getToolkit().beep();
            int keluar = JOptionPane.showConfirmDialog(this, "Anda Yakin Ingin Meghapus "
                    + "Ini..?","PERINGATAN",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
            if(keluar==JOptionPane.YES_OPTION){
                try {
                    koneksi();
                    String sql = "delete from matakuliah_2221026 where Kodemtk='"+ JtxtKDmtk.getText() +"'";
                    cn.executeUpdate(sql);
                    conn.close();
                    
                    tampildata();
                    bersih();
                    
                    JtxtKDmtk.setEnabled(true);
                    JBTnSave.setEnabled(true);
                    JBtnEdit.setEnabled(false);
                    JBtnHapus.setEnabled(false);
                    JtxtKDmtk.requestFocus();
                    
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"Deleting failed..");
                }    
            }
        } catch (Exception e) {
            
        }
        
    }//GEN-LAST:event_JBtnHapusActionPerformed

    private void tabelinputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelinputMouseClicked
        // TODO add your handling code here:
        int row = tabelinput.getSelectedRow();

String a = tabelinput.getValueAt(row, 0).toString();
String b = tabelinput.getValueAt(row, 1).toString();
String c = tabelinput.getValueAt(row, 2).toString();

        
        JtxtKDmtk.setText(a);
        JTxtNamaMtk.setText(b);
        JTxtJmlsks.setText(c);
        
        JtxtKDmtk.setEnabled(false);
        JBTnSave.setEnabled(false);
        JBtnEdit.setEnabled(true);
        JBtnHapus.setEnabled(true);
    }//GEN-LAST:event_tabelinputMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inputmatkul().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTnSave;
    private javax.swing.JButton JBtnEdit;
    private javax.swing.JButton JBtnHapus;
    private javax.swing.JTextField JTxtJmlsks;
    private javax.swing.JTextField JTxtNamaMtk;
    private javax.swing.JTextField JtxtKDmtk;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelinput;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
