/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package praktikum.pkg9;
import java.sql.ResultSet;
import java.sql.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.*;
import javax.swing.table.*;
/**
 *
 * @author CHAIRULAW
 */
public class mahasiswa extends javax.swing.JFrame {
    public Connection conn;
    public Statement cn;

    /**
     * Creates new form mahasiswa
     */
    
    
    public mahasiswa() {
        initComponents();
        tampil();
        bersih();
        cbkelamin.removeAllItems();
        cbkelamin.addItem("LAKI-LAKI");
        cbkelamin.addItem("PEREMPUAN");
        
        cbfakultas.removeAllItems();
        cbfakultas.addItem("TEKNOLOGI INFORMASI");
        cbfakultas.addItem("TEKNOLOGI INSDUSTRI");
        
        cbprodi.removeAllItems();
        cbprodi.addItem("SISTEM INFORMASI");
        cbprodi.addItem("TEKNIK INDUSTRI");
        cbprodi.addItem("MANAJEMEN REKAYASA");
        cbprodi.addItem("PERDAGANGAN INTERNASIONAL");
        cbprodi.addItem("DESIGN KOMUNIKASI VISUAL");
    }
    
     public void koneksi(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection
        ("jdbc:mysql://localhost:3306/dbakademik","root","");
            cn= conn.createStatement();
        }catch (Exception e){JOptionPane.showMessageDialog(null,"koneksi gagal..");
        System.out.println(e.getMessage());
        }
    }
     
        void tampil(){
       DefaultTableModel tabelnyo = new DefaultTableModel();
       tabelnyo.addColumn("NIM MAHASISWA");
       tabelnyo.addColumn("NAMA MAHASISWA");
       tabelnyo.addColumn("TEMPAT LAHIR");
       tabelnyo.addColumn("TANGGAL LAHIR");
       tabelnyo.addColumn("NO HP");
       tabelnyo.addColumn("ALAMAT");
       tabelnyo.addColumn("JENIS KELAMIN");
       tabelnyo.addColumn("NAMA ORTU");
       tabelnyo.addColumn("FAKULTAS");
       tabelnyo.addColumn("PRODI");

       try{
           koneksi();
           String sql = "SELECT * FROM Mahasiswa_2221026";
           ResultSet rs = cn.executeQuery(sql);
           while (rs.next()) {
               tabelnyo.addRow(new Object[]{
                   rs.getString(1),
                   rs.getString(2),
                   rs.getString(3),
                   rs.getString(4),
                   rs.getString(5),
                   rs.getString(6),
                   rs.getString(7),
                   rs.getString(8),
                   rs.getString(9),
                   rs.getString(10),
               });
           }

           tabelmhs.setModel(tabelnyo);
       }catch (Exception e){
           JOptionPane.showMessageDialog(null, "Ada Kesalahan");
       }
        }
     
        void bersih(){
        txtcari.setText("");
        txtnim.setText("");
        txtnama.setText("");
        txttmptlahir.setText("");
        txtnohp.setText("");
        txtalamat.setText("");
        cbkelamin.setSelectedItem("");
        txtortu.setText("");
        cbfakultas.setSelectedItem("");
        cbprodi.setSelectedItem("");
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtnim = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txttmptlahir = new javax.swing.JTextField();
        txtnohp = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        cbkelamin = new javax.swing.JComboBox<>();
        txtortu = new javax.swing.JTextField();
        cbfakultas = new javax.swing.JComboBox<>();
        cbprodi = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelmhs = new javax.swing.JTable();
        btsimpan = new javax.swing.JButton();
        btedit = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        btkeluar = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        jRadioButton1.setText("jRadioButton1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel1.setText("INPUT DATA MAHASISWA");

        jLabel2.setText("CARI BERDASARKAN NIM/NAMA MAHASISWA");

        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });

        jLabel3.setText("NIM MAHASISWA");

        jLabel4.setText("NAMA MAHASISWA");

        jLabel5.setText("TEMPAT LAHIR");

        jLabel6.setText("TANGGAL LAHIR");

        jLabel7.setText("NO HP");

        jLabel8.setText("ALAMAT");

        jLabel9.setText("JENIS KELAMIN");

        jLabel10.setText("NAMA ORTU");

        jLabel11.setText("FAKULTAS");

        jLabel12.setText("PROGRAM STUDI");

        txtnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnimActionPerformed(evt);
            }
        });

        cbkelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbfakultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbprodi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tabelmhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelmhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelmhsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelmhs);

        btsimpan.setText("SIMPAN");
        btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsimpanActionPerformed(evt);
            }
        });

        btedit.setText("EDIT");
        btedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditActionPerformed(evt);
            }
        });

        bthapus.setText("HAPUS");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });

        btkeluar.setText("KELUAR");
        btkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbfakultas, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtnim)
                                    .addComponent(cbprodi, 0, 373, Short.MAX_VALUE)
                                    .addComponent(txtortu)
                                    .addComponent(cbkelamin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtnohp)
                                    .addComponent(txtalamat)
                                    .addComponent(txtnama)
                                    .addComponent(txttmptlahir)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btsimpan)
                .addGap(52, 52, 52)
                .addComponent(btedit)
                .addGap(67, 67, 67)
                .addComponent(bthapus)
                .addGap(66, 66, 66)
                .addComponent(btkeluar)
                .addGap(207, 207, 207))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(txtnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(txttmptlahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtnohp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(52, 52, 52)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel9))
                                    .addComponent(cbkelamin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(73, 73, 73)
                                .addComponent(jLabel10))
                            .addComponent(txtortu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 568, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 30, Short.MAX_VALUE)))))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbfakultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btsimpan)
                    .addComponent(btedit)
                    .addComponent(bthapus)
                    .addComponent(btkeluar))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbprodi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsimpanActionPerformed
        // TODO add your handling code here:
        try{
        koneksi();
        String sql= "insert into Mahasiswa_2221026 values ('"+ txtnim.getText() +"','"+
                txtnama.getText() +"','"+ txttmptlahir.getText() +"','"+ ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText() +"','"+
                        txtnohp.getText() +"','"+ txtalamat.getText()+"','"+ cbkelamin.getSelectedItem() +"','"+ txtortu.getText() +"','"+
                        cbfakultas.getSelectedItem() +"','"+ cbprodi.getSelectedItem() +"')";
                        cn.executeUpdate(sql);
                        conn.close();
                        tampil();
        bersih();
        JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Proses Penyimpanan Data Gagal" + e);
        }
                        
        
    }//GEN-LAST:event_btsimpanActionPerformed

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed
        // TODO add your handling code here:
        try{
        koneksi();
        String sql="Update Mahasiswa_2221026 set tanggallahir='"+ ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText()+"',namamhs='"+ 
                txtnama.getText()+"',tempatlahir='"+ txttmptlahir.getText()+"',nohp='"+ txtnohp.getText()+"',alamat='"+ 
                txtalamat.getText()+ "',jeniskelamin='"+ cbkelamin.getSelectedItem()+"',namaortu='"+ txtortu.getText() +"',fakultas='"+ 
                cbfakultas.getSelectedItem() +"',prodi='"+ cbprodi.getSelectedItem() +"' where nimmhs='"+ txtnim.getText() +"'";
        cn.executeUpdate(sql);
        conn.close();
        tampil();
        bersih();
        
        btsimpan.setEnabled(true);
        
        JOptionPane.showMessageDialog(null, "Data Berhasil Di Update");
        
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Update Data Gagal");
        }
    }//GEN-LAST:event_bteditActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        // TODO add your handling code here:
        try{
        koneksi();
        String sql="delete from Mahasiswa_2221026 where nimmhs='"+ txtnim.getText() +"'";
        cn.executeUpdate(sql);
        conn.close();
        tampil();
        bersih();
        
         JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Succes To Delete");
        }
    }//GEN-LAST:event_bthapusActionPerformed

    private void btkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btkeluarActionPerformed

    private void tabelmhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelmhsMouseClicked
        // TODO add your handling code here:
       int row =0;
        if(evt.getClickCount()==1){
            row=tabelmhs.getSelectedRow();
        txtnim.setText(tabelmhs.getValueAt(row,0).toString());
        txtnama.setText(tabelmhs.getValueAt(row,1).toString());
        txttmptlahir.setText(tabelmhs.getValueAt(row,2).toString());
        jDateChooser1.setDateFormatString(tabelmhs.getValueAt(row,3).toString());
        txtnohp.setText(tabelmhs.getValueAt(row,4).toString());
        txtalamat.setText(tabelmhs.getValueAt(row,5).toString());
        cbkelamin.setSelectedItem(tabelmhs.getValueAt(row,6).toString());
        txtortu.setText(tabelmhs.getValueAt(row,6).toString());
        cbfakultas.setSelectedItem(tabelmhs.getValueAt(row,6).toString());
        cbprodi.setSelectedItem(tabelmhs.getValueAt(row,6).toString());
        
        btsimpan.setEnabled(false);
        }
    }//GEN-LAST:event_tabelmhsMouseClicked

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
      DefaultTableModel tabelnyo=new DefaultTableModel();
       tabelnyo.addColumn("NIM MAHASISWA");
       tabelnyo.addColumn("NAMA MAHASISWA");
       tabelnyo.addColumn("TEMPAT LAHIR");
       tabelnyo.addColumn("TANGGAL LAHIR");
       tabelnyo.addColumn("NO HP");
       tabelnyo.addColumn("ALAMAT");
       tabelnyo.addColumn("JENIS KELAMIN");
       tabelnyo.addColumn("NAMA ORTU");
       tabelnyo.addColumn("FAKULTAS");
       tabelnyo.addColumn("PRODI");
            
            try{
            koneksi();
            String sql = "Select * from mahasiswa_2221026 where " +"NimMhs ='" + txtcari.getText() + "' or " 
                    +"NamaMhs like '%" + txtcari.getText() + "%'";
        ResultSet rs = cn.executeQuery(sql);
        while (rs.next()) {
            tabelnyo.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),
                rs.getString(6),
                rs.getString(7),
                rs.getString(8),
                rs.getString(9),
                rs.getString(10),
            });
        }
        tabelmhs.setModel(tabelnyo);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Terjadi Kesalahan " + e);
        }
    }//GEN-LAST:event_txtcariActionPerformed

    private void txtnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btedit;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btkeluar;
    private javax.swing.JButton btsimpan;
    private javax.swing.JComboBox<String> cbfakultas;
    private javax.swing.JComboBox<String> cbkelamin;
    private javax.swing.JComboBox<String> cbprodi;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelmhs;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnim;
    private javax.swing.JTextField txtnohp;
    private javax.swing.JTextField txtortu;
    private javax.swing.JTextField txttmptlahir;
    // End of variables declaration//GEN-END:variables
}
